NUM_EMOTIONS = 2

# Maps midi file name to emotions
# Emotions are a tuple: happiness (1 = sad, 10 = happy), excitement (1 = calm, 10 = exciting)
EMOTIONS = {
	'[Full] Kaibutsu midi': (3, 7),
	'_〜Sing_Girls〜': (8, 6),
	'Aka no Kakera (2)': (3, 6),
	'Akatsuki no Requiem (暁の鎮魂歌)': (2, 5),
	'All in good time': (7, 3),
	'Amnanesis': (1, 2),
	'Animenz - Exist': (5, 8),
	'Animenz - Secret Base': (1, 4),
	'AQUA': (2, 3),
	'Aruji Naki Sono Koe': (4, 4),
	'Ashita e no Kaerimichi': (4, 6),
	'Ashita_no_Kimi_sae_Ireba_Ii': (7, 6),
	'Bad Apple!!': (3, 9),
	'Believe_in_Magic': (6, 8),
	'Bios': (4, 7),
	'Boku to Kimi no Lullaby': (3, 3),
	'Bouken Desho Desho (Animenz)': (9, 4),
	'Brave Heart': (9, 10),
	'Brave Song (1)': (1, 3),
	'Butterfly': (3, 4),
	'Butterfly_in_The_Still': (4, 2),
	'Centimeter TV SIZE': (10, 10),
	'Cha-la Head-Cha-La': (9, 7),
	'Clannad - Dango Daikazoku (ZenSoul)': (3, 2),
	'Clockwork Planet OP FULL - Piano Arrangement by RoranZ': (6, 8),
	'Confronting YouTubes Algorithm': (3, 8),
	'Cras numquam scire': (2, 3),
	'Crossing Field (Animenz)': (7, 9),
	'Daydream Syndrome': (5, 8),
	'Death_Parade_OST_-_Moonlit_Night (2)': (2, 2),
	'Departure!': (4, 5),
	'Dont Say Lazy (Animenz)': (8, 10),
	'Door': (6, 1),
	'Dragon ball Super-ED9-Haruka': (5, 4),
	'Dream theme from Nazo no Kanojo X': (3, 7),
	'EASY LOVE (Full ver.)': (9, 10),
	'Enter Enter Mission': (8, 9),
	'Esoragoto': (6, 8),
	'Eternal City - Piano Suite': (2, 3),
	'Euterpe': (2, 5),
	'Fallen Angel': (3, 7),
	'Fate Apocrypha ED - Dèsir (Piano Arrangement by RoranZ)': (2, 6),
	'Fate Apocrypha ED': (3, 5),
	'Fight!! (Full ver.)': (9, 6),
	'Fly_Me_To_The_Star': (4, 3),
	'Fukisokusei Entropy (Full ver.)': (3, 9),
	'FULLBeastars_Opening_2_Kaibutsu__-_YOASOBI': (4, 7),
	'Gentle_Comet': (2, 8),
	'glory': (6, 9),
	'GO GO Maniac': (8, 8),
	'go_forward': (4, 9),
	'God knows...': (5, 7),
	'Gudafuwa Every Day (Full ver.)': (10, 9),
	'Guren no Yumiya': (5, 10),
	'Hanezeve Caradhina': (2, 7),
	'Hi_No_Ito_Rinne_No_Gemini': (4, 8),
	'Hikari no Senritsu': (3, 4),
	'History_Maker': (8, 3),
	'Horimiya OP': (6, 5),
	'I_love': (7, 6),
	'Ichiban no Takaromono (Animenz)': (2, 5),
	'Imagination (Animenz)': (10, 4),
	'Imperfect (Full ver.)': (3, 8),
	'Iron-Blooded Orphan Piano Ver': (2, 1),
	'Jinsei Easy (Full ver.)': (8, 9),
	'Kanashimi no ato ni': (1, 4),
	'Karakai Jouzu no Takagi-san Season 2 OP - Zero Centimeters [Piano MIDI]': (7, 6),
	'Karma（「憂国のモリアーティ」メインテーマ）': (3, 8),
	'Kibou ni Tsuite': (6, 6),
	'Kibou no Hana': (2, 3),
	'Kimi ni Matsuwaru Mystery': (4, 6),
	'Kimi no Moji (midi)': (3, 4),
	'Kisetsu wa tsugi tsugi (ZenSoul)': (2, 6),
	'Koko Kara Hajimaru Monogatari': (3, 3),
	'Kokoro no Senritsu': (3, 5),
	'Komorebi no Yell (Full ver.)': (4, 7),
	'kos-op-1': (6, 8),
	'Kuusou Mesorogiwi': (5, 8),
	'Laputa_-_Castle_in_the_Sky__advanced': (3, 2),
	'Level 5 -judgelight-_v2': (8, 8),
	'Licht und Schatten - Tokyo Ghoul OST (ZenSoul)': (3, 6),
	'Light my Fire': (5, 9),
	'Little Busters!': (7, 5),
	'Longing for! (Full ver.)': (8, 9),
	'Lumis Eterne': (5, 2),
	'Magia': (4, 7),
	'Megumeru - Cuckool mix 2007 -': (1, 4),
	'Melissa (Animenz ver)': (7, 7),
	'midi': (4, 8),
	'mikan sora': (4, 2),
	'Mikansei Stride': (8, 6),
	'Moonlight Densetsu': (6, 6),
	'Music_S.T.A.R.T!': (7, 6),
	'My Dearest': (3, 8),
	'My Soul Your Beats (1)': (2, 8),
	'Nagi Animenz': (3, 5),
	'Namae no nai Kaibutsu': (5, 5),
	'Niji no Ressha': (6, 7),
	'Noragami Aragoto OP - Kyouran Hey Kids! (ZenSoul)': (7, 9),
	'Oath Sign': (3, 6),
	'Omoide Shiritori (Full ver.)': (4, 7),
	'One Last Kiss': (4, 7),
	'Only my railgun': (5, 9),
	'Orion ': (6, 5),
	'OST#21 - 距離感': (1, 2),
	'Owari_no_Uta': (2, 1),
	'pendulumbeat': (5, 7),
	'Perfect Day (ZenSoul)': (3, 3),
	'Realize TV_SIZE': (4, 6),
	'REDLINE DAY': (3, 6),
	'Reimei': (2, 6),
	'Requiem of Silence': (2, 9),
	'running in the 90s': (6, 7),
	'ryuga theme': (5, 7),
	'Ryuuou no Oshigoto! - Korekara': (7, 6),
	'Sad_Reminiscence': (2, 2),
	'Sagitta Luminis': (3, 2),
	'Sakura': (4, 7),
	'Scarlet Ballet': (9, 7),
	'Seize The Day (Full ver.)': (10, 7),
	'Senbonzakura': (7, 8),
	'Shoukoku no Altair OP': (3, 6),
	'Sincerely_v2 (Animenz)': (2, 6),
	'Sis puella magica!': (5, 3),
	'Sis_puella_magica! OST': (4, 4),
	'Sister\'s Noise': (7, 8),
	'Snow Halation by Maestozo midi': (9, 7),
	'Sobakasu': (8, 4),
	'Sparkling Daydream': (3, 8),
	'Start_DASH!!': (4, 6),
	'Strobe Memory midi': (5, 7),
	'Suite for Pars I - Moment of Pars': (5, 8),
	'swing_pendulum': (3, 6),
	'Tabibito no Uta (Full ver.)': (6, 6),
	'Tadaima (Full ver.)': (10, 3),
	'Taiga yo Tomo ni Naitekure (TV size)': (6, 8),
	'The Everlasting Guilty Crown (Animenz)': (5, 5),
	'The_Glory_Days': (8, 10),
	'ThemE Of ReLieF 第1楽章 -MinoR-': (3, 3),
	'Toki Tsukasadoru Juuni no Meiyaku': (2, 5),
	'Trust me': (7, 7),
	'Truth_and_Light_piano_ver.': (2, 4),
	'Tsugihagi Moyou (Full ver.)': (8, 6),
	'Two faced lovers': (6, 9),
	'uchiage hanabi': (3, 6),
	'unfinished': (4, 8),
	'Unlasting (Animenz)': (1, 4),
	'Unravel - Tokyo Ghoul Root A Piano Recreation (ZenSoul)': (3, 7),
	'Ushio': (8, 2),
	'Warratte Itakute': (2, 2),
	'Wiosna': (4, 1),
	'With_the_Wind': (6, 8),
	'Writing_Life': (3, 5),
	'Yasashii Boukyaku': (6, 2),
	'Yasashisa no Riyuu': (5, 6),
	'Yasashisa_no_Riyuu_(優しさの理由)': (3, 8),
	'Yoake Umarekuru Shoujo': (3, 8),
	'YOASOBI　『怪物』': (5, 7),
	'YOASOBI_-_Piano_Solo_Reduction_Intermediate': (6, 5),
	'Yume wa Nando mo Umarekawaru': (5, 7),
	'Yume wo Kakeru! (Full ver.)': (5, 8),
	'Yumetourou_夢灯籠': (2, 3),
	'Zankoku na Yume to Nemure (Full ver.)': (5, 9),
	'Zankyou no Terror OST - Kvak': (3,2 ),
	'ZZZ': (4, 6),
	'スターナイトスノウ': (6, 8),
}